[project]
name = "binary-demo"
version = "0.1.0"
description="A minimal example package with Pybind11"
readme = "README.md"
authors = [
    { name = "Jiri Klic", email = "web@jiriklic.com" }
]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

dependencies = []

[dependency-groups]
dev = [
    "conan>=2.17.0",
    "jupyterlab>=4.4.3",
    "pytest>=8.3.5",
]

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

[tool.scikit-build-core-conan]
path = "."
build = "missing"
profile = ".conan2/profiles/default"
options = []
settings = []
config = []
generators = ["CMakeToolchain", "CMakeDeps"]
output-folder = "build"

[build-system]
requires = [
    "scikit-build-core>=0.11.5",
    "scikit-build-core-conan>=0.7.1",
    "pybind11"
]
build-backend = "scikit_build_core_conan.build"

